### ISSUE TITLE
test_sorting_all is flaky

### ISSUE THREAD

**Issue by littledivy** [three-em/3em#107]
```
---- test::test_sorting_all stdout ----
thread 'test::test_sorting_all' panicked at 'Invalid amount of transactions', crates/executor/lib.rs:378:9
stack backtrace:
   0: rust_begin_unwind
             at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/panicking.rs:498:5
   1: core::panicking::panic_fmt
             at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/core/src/panicking.rs:107:14
   2: three_em_executor::test::test_sorting_all::{{closure}}
             at ./lib.rs:378:9
   3: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/core/src/future/mod.rs:80:19
   4: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/core/src/future/future.rs:119:9
   5: tokio::runtime::basic_scheduler::Inner<P>::block_on::{{closure}}::{{closure}}
             at /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.13.0/src/runtime/basic_scheduler.rs:228:62
   6: tokio::coop::with_budget::{{closure}}
             at /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.13.0/src/coop.rs:106:9
   7: std::thread::local::LocalKey<T>::try_with
             at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/thread/local.rs:399:16
   8: std::thread::local::LocalKey<T>::with
             at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/thread/local.rs:375:9
   9: tokio::coop::with_budget
             at /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.13.0/src/coop.rs:99:5
  10: tokio::coop::budget
             at /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.13.0/src/coop.rs:76:5
  11: tokio::runtime::basic_scheduler::Inner<P>::block_on::{{closure}}
             at /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.13.0/src/runtime/basic_scheduler.rs:228:39
  12: tokio::runtime::basic_scheduler::enter::{{closure}}
             at /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.13.0/src/runtime/basic_scheduler.rs:337:29
  13: tokio::macros::scoped_tls::ScopedKey<T>::set
             at /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.13.0/src/macros/scoped_tls.rs:61:9
  14: tokio::runtime::basic_scheduler::enter
             at /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.13.0/src/runtime/basic_scheduler.rs:337:5
  15: tokio::runtime::basic_scheduler::Inner<P>::block_on
             at /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.13.0/src/runtime/basic_scheduler.rs:218:9
  16: tokio::runtime::basic_scheduler::InnerGuard<P>::block_on
             at /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.13.0/src/runtime/basic_scheduler.rs:489:9
  17: tokio::runtime::basic_scheduler::BasicScheduler<P>::block_on
             at /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.13.0/src/runtime/basic_scheduler.rs:178:24
  18: tokio::runtime::Runtime::block_on
             at /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.13.0/src/runtime/mod.rs:461:46
  19: three_em_executor::test::test_sorting_all
             at ./lib.rs:373:5
  20: three_em_executor::test::test_sorting_all::{{closure}}
             at ./lib.rs:350:9
  21: core::ops::function::FnOnce::call_once
             at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/core/src/ops/function.rs:227:5
  22: core::ops::function::FnOnce::call_once
             at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/core/src/ops/function.rs:227:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

https://github.com/three-em/3em/runs/4892860510?check_suite_focus=true#step:5:746

**Comment by littledivy** [comment]
Use https://github.com/denoland/flaky_test as a workaround

**Comment by andreespirela** [comment]
@littledivy I'll take this
